### PR TITLE
SIMD-0128: Migrate Address Lookup Table Program to Core BPF

### PR DESCRIPTION
**Pull request by buffalojoec**
Migrate the Address Lookup Table program to Core BPF.

### CODE REVIEW

**Comment by buffalojoec** [comment]
I'm leaving this as a draft until the new Get Sysvar syscall from SIMD 0127 has been implemented in Agave.

Once the implementation is complete, the Core BPF Address Lookup Table program can be updated to exactly match the original use of slot hashes for lookup table cooldown, making this SIMD accurate.

**Comment by buffalojoec** [comment]
Ready to go. IDL: https://github.com/solana-program/address-lookup-table/blob/main/program/idl.json

**Review by joncinque — APPROVED** [review]
Looks good to me!

**Review by joncinque — DISMISSED** [review]
Great, thanks!

**Comment by buffalojoec** [comment]
@lheeger-jump gentle nudge here, please.

**Review by topointon-jump — APPROVED** [review]
Looks good! Could you add a link to the new program source code?

**Review by joncinque — APPROVED** [review]

**Pull request merged**
